### ISSUE TITLE
Lighting タブで Stencil が正しく描画されない

### ISSUE THREAD

**Issue by nekobako** [lilxyzw/lilAvatarUtils#1]
PreviewRenderUtility が生成する RenderTexture の depth が 16bit のため、Lighting タブで Stencil が正しく描画されないようです。
また、カメラの設定にもよりますが Scene View よりも z-fight が発生しやすくなっています。

Unity 2019.4.31f1 での様子です。
上段: 青い Cube の中にある赤い Cube を Stencil で見えるようにしたもの
下段: 青い Cube を赤い Cube より少し (2e-05) だけ手前に置いたもの
https://user-images.githubusercontent.com/4340778/225014237-97593774-6965-4e08-ad91-e0f4a9f65049.mp4

Unity 2020.1.0a5 からは 32bit に変更されているようです。
https://github.com/Unity-Technologies/UnityCsReference/commit/32bd3a1c008265df4cd53b556446fab60f964834#diff-76e0b225bb4aa14f0eddd8e5029671d71971dbc6ca2eac07a3f50751f24eb682L283

**Comment by lilxyzw** [comment]
PRの方は開発ブランチの方へMergeいたしました。こちらの修正はバージョンアップ時に反映いたします。

**Comment by nekobako** [comment]
ありがとうございます！
